# Generated by Django 2.1.1 on 2018-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True, verbose_name='URL для парсинга')),
                ('timeshift', models.PositiveIntegerField(default=0, verbose_name='Время ожидания перед началом парсинга в секундах')),
            ],
            options={
                'verbose_name': 'Очередь парсинга',
                'verbose_name_plural': 'Очередь парсинга',
            },
        ),
    ]
