# Generated by Django 2.1.1 on 2018-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlqueue',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Флаг выполнения'),
        ),
    ]
